import { pgTable, serial, text, integer, timestamp, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// Layer 1/2: Decisions generated by TerraIQ or other agents
export const decisionsTable = pgTable("decisions", {
  id: serial("id").primaryKey(),
  sourceAgent: text("source_agent").notNull(), // e.g. 'TerraIQ', 'FieldLot'
  decisionType: text("decision_type").notNull(), // e.g. 'BUY_ASSET', 'ISSUE_CONTRACT'
  context: jsonb("context"), // The data/context used to make the decision
  proposedAction: text("proposed_action").notNull(),
  status: text("status").notNull().default("pending_audit"), // pending_audit, validated, rejected
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

// Layer 3: Audit validations run against a decision
export const validationsTable = pgTable("validations", {
  id: serial("id").primaryKey(),
  decisionId: integer("decision_id").references(() => decisionsTable.id),
  module: text("module").notNull(), // e.g. 'Source Verification', 'Financial Validator', 'Legal Compliance'
  confidenceScore: integer("confidence_score").notNull(), // 0-100
  riskLevel: text("risk_level").notNull(), // LOW, MEDIUM, HIGH
  findings: jsonb("findings"), // Array of string findings
  recommendation: text("recommendation"), // APPROVED, FLAGGED, REJECTED
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// Layer 4: Final Trust Score aggregation
export const trustScoresTable = pgTable("trust_scores", {
  id: serial("id").primaryKey(),
  decisionId: integer("decision_id").references(() => decisionsTable.id),
  overallScore: integer("overall_score").notNull(), // 0-100
  overallRisk: text("overall_risk").notNull(), // LOW, MEDIUM, HIGH
  finalVerdict: text("final_verdict").notNull(), // APPROVED, REJECTED
  executiveSummary: text("executive_summary"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertDecisionSchema = createInsertSchema(decisionsTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertDecision = z.infer<typeof insertDecisionSchema>;
export type Decision = typeof decisionsTable.$inferSelect;
